### ISSUE TITLE
endElement() 호출시 NullPointerException 발생

### ISSUE THREAD

**Issue by woojh3690** [neolord0/hwpxlib#1]
[test.zip](https://github.com/neolord0/hwpxlib/files/11220809/test.zip)
위 한글 파일을 읽을려고 하면 아래와 같은 에러가 발생합니다.

```
java.lang.NullPointerException
	at kr.dogfoot.hwpxlib.reader.common.XMLFileReader.endElement(XMLFileReader.java:94)
	at kr.dogfoot.hwpxlib.reader.ContentFilesReader.endElement(ContentFilesReader.java:85)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2969)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:507)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:867)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:796)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:142)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:644)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:328)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:196)
	at kr.dogfoot.hwpxlib.reader.common.XMLFileReader.read(XMLFileReader.java:31)
	at kr.dogfoot.hwpxlib.reader.common.XMLFileReader.read(XMLFileReader.java:37)
	at kr.dogfoot.hwpxlib.reader.ContentFilesReader.read(ContentFilesReader.java:38)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.packagedFiles(HWPXReader.java:113)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.read(HWPXReader.java:80)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.fromFile(HWPXReader.java:31)
	at kr.co.iwaz.Main.main(Main.java:22)
```

**Comment by neolord0** [comment]
안녕하세요..
테스트 해보니.. 제가 테스트한 2014버전과 다른 부분이 있어서 오류가 난 거 같습니다.
수정하여 올렸습니다.  다시 받아서 테스트 해보세요.

**Comment by woojh3690** [comment]
마지막 커밋이 한달전이라고 하는데 혹시 이 레파지토리 말고 다른 레파지토리가 있을까요?

**Comment by neolord0** [comment]
정신이 없어서... 커밋만 하고 푸시를 안 했습니다.
^^;

**Comment by woojh3690** [comment]
hwpx 파일 잘 읽는 거 확인 하였습니다. 혹시 읽어들인 HWPXFile 에서 텍스트만 추출하는 방법은 아직 없는걸까요?
