### ISSUE TITLE
SAXParser parse 에러 입니다.

### ISSUE THREAD

**Issue by yundongjun** [neolord0/hwpxlib#4]
Exception in thread "main" java.lang.NullPointerException
	at kr.dogfoot.hwpxlib.reader.common.XMLFileReader.endElement(XMLFileReader.java:93)
	at kr.dogfoot.hwpxlib.reader.ContentFilesReader.endElement(ContentFilesReader.java:90)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:184)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1377)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
	at kr.dogfoot.hwpxlib.reader.common.XMLFileReader.read(XMLFileReader.java:31)
	at kr.dogfoot.hwpxlib.reader.common.XMLFileReader.read(XMLFileReader.java:37)
	at kr.dogfoot.hwpxlib.reader.ContentFilesReader.read(ContentFilesReader.java:43)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.packagedFiles(HWPXReader.java:113)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.read(HWPXReader.java:80)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.fromFile(HWPXReader.java:31)
	at kr.dogfoot.hwpxlib.reader.HWPXReader.fromFilepath(HWPXReader.java:21)
	at com.dreamsecurity.util.HwpxTextExtract.main(HwpxTextExtract.java:15)

이 와 같은 에러가 발생하고 있습니다.

이미지로 인하여 발생하는 문제인 것 같은데 원인이 확실하지 않아 질문드립니다.

테스트할 수 있는 파일입니다.
https://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20230705861::00::2::2 해당 url에서 다운로드 받을 수 있습니다.

**Comment by neolord0** [comment]
안녕하세요
이 오류는 수정하였습니다. 
hh:head 노드 안에 hh:metaTag 노드가 포함돼서 오류가 발생된 겁니다.
문서에 없던 노드가 계속 추가 되네요 --;
